Feature/frontend rust
jbis9051/life256 pull request #29
Opened 2023-07-08 14:58 UTC by jbis9051

2023-07-11 04:27 UTC, gannonsmith requested changes
I ignored error handling in the name of progress. Looking forward to reviewing features with less code in the future.

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/db/migrations/20220528030155_initial.up.sql
> +
Why is this done instead of initializing the fk the same way every other fk is?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/db/migrations/20220528030155_initial.up.sql
> +
Do models need to be updated?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/migrations/account/20230524013755_initial.up.sql
> +    user_uuid TEXT NOT NULL,
Foreign key?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/migrations/account/20230524013755_initial.up.sql
> +    user_uuid TEXT NOT NULL,
On Delete Cascade?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/migrations/account/20230524013755_initial.up.sql
> +    group_uuid TEXT NOT NULL,
Foreign Keys?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/migrations/account/20230524013755_initial.up.sql
> +    location_date INTEGER NOT NULL,
```suggestion
    location_date DATETIME NOT NULL,
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/migrations/account/20230524013755_initial.up.sql
> +    received_date DATETIME NOT NULL
```suggestion
    received_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/api/client.rs
> +        Ok(key_package_in)
condense

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/api/client.rs
> +}
Missing PATCH and DELETE for client

2023-07-11 04:27 UTC, gannonsmith commented on docs/API_ROUTES.md
Consider adding "/v1/" to api routes

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/api/user.rs
> +            .get(&format!("{}/v1/user/reset/{}", self.domain, token))
```suggestion
            .get(&format!("{}/v1/user/reset?", self.domain))
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/api/user.rs
> +            .get(&format!("{}/v1/user/reset/{}", self.domain, token))
Not sure exactly how .query() works with an object

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/api/user.rs
> +    pub async fn search(&self, query: String) -> Result<Vec<PublicUser>, reqwest::Error> {
Missing documentation for /v1/user/search in API docs

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/application_message.rs
> +    pub timestamp: i64,
surely there is a better type for a timestamp?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/helper/bubble_group.rs
> +    }
Why does this exist?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/helper/bubble_group.rs
> +        if matches!(self.group.state_changed(), InnerState::Changed) {
Is matches! macro needed?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/helper/helper.rs
> +        // TODO: consider storing this directly in GlobalAccountData
Consider

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/helper/helper.rs
> +pub fn parse_identity(identity: &[u8]) -> Result<(Uuid, Uuid), ParseIdentityError> {
Move ParseIdentityError to Error enum in frontend/src/lib.rs

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/helper/resource_fetcher.rs
> +            client.create(&self.account_db).await?;
Race Condition? Maybe we should add model for "try_create"?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/helper/resource_fetcher.rs
> +        let mut user: User = api_user.into();
```suggestion
        let mut user: User = self.api.get_user(user_uuid).await?.into();
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/js_interface/client.rs
> +        let num_key_packages = 100;
why 100?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/js_interface/group.rs
> +        // TODO what happens if we add a member that is already in the group?
Can we just not permit this in frontend?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/js_interface/group.rs
> +    pub async fn remove_member(&self, group_uuid: Uuid, user_uuid: Uuid) -> Result<(), Error> {
should we make this remove_members() and pass a Vec of user_uuids instead?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/js_interface/location.rs
> +    pub async fn get_num_location(
```suggestion
    pub async fn get_num_locations(
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/js_interface/message.rs
> +            // TODO: process message
?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/mls_provider/keystore.rs
> +        self.0.to_string() == other.0.to_string() // TODO: This is not a good way to compare errors
true

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/mls_provider/mod.rs
> +    }
why not just make these attributes public?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/group.rs
> +        Ok(locations.iter().map(Group::from).collect())
```suggestion
        Ok(locations.iter().map(|g| g.into()).collect())
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/group.rs
> +        Ok(locations.iter().map(Group::from).collect())
idk if this is better or even works

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/inbox.rs
> +            (&sqlx::query("INSERT INTO inbox (message, received_date) VALUES (?, ?) RETURNING *")
```suggestion
            (&sqlx::query("INSERT INTO inbox (message, received_date) VALUES (?, ?) RETURNING *;")
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/inbox.rs
> +        sqlx::query("SELECT * FROM inbox ORDER BY received_date ASC")
```suggestion
        sqlx::query("SELECT * FROM inbox ORDER BY received_date ASC;")
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/inbox.rs
> +        sqlx::query("DELETE FROM inbox WHERE id = ?")
```suggestion
        sqlx::query("DELETE FROM inbox WHERE id = ?;")
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/keystore.rs
> +        sqlx::query("DELETE FROM keystore WHERE key = $1; INSERT INTO keystore (key, value, type_name) VALUES ($1,$2, $3);")
nit: Could separate these into two queries but use one transaction

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/location.rs
> +            location_date,
?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/location.rs
> +        *self = (&sqlx::query("INSERT INTO location (client_uuid, group_uuid, longitude, latitude, location_date, raw) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *")
```suggestion
        *self = (&sqlx::query("INSERT INTO location (client_uuid, group_uuid, longitude, latitude, location_date, raw) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *;")
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/location.rs
> +        let locations = sqlx::query("SELECT * FROM location WHERE location_date < $1 AND group_uuid = $2 AND client_uuid = $3 ORDER BY location_date DESC LIMIT $4")
```suggestion
        let locations = sqlx::query("SELECT * FROM location WHERE location_date < $1 AND group_uuid = $2 AND client_uuid = $3 ORDER BY location_date DESC LIMIT $4;")
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/frontend/src/models/account/location.rs
> +        let count = sqlx::query("SELECT COUNT(*) as count FROM location WHERE location_date BETWEEN $1 AND $2 AND group_uuid = $3 AND client_uuid = $4")
```suggestion
        let count = sqlx::query("SELECT COUNT(*) as count FROM location WHERE location_date BETWEEN $1 AND $2 AND group_uuid = $3 AND client_uuid = $4;")
```

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/server/Cargo.toml
> +sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "sqlite", "postgres", "migrate", "uuid", "chrono"] }
sqlite in backend?

2023-07-11 04:27 UTC, gannonsmith commented on packages/rust/server/src/models/user.rs
> +    pub async fn client(&self, db: &DbPool) -> Result<Option<Client>, sqlx::Error> {
```suggestion
    pub async fn primary_client(&self, db: &DbPool) -> Result<Option<Client>, sqlx::Error> {
```

2023-07-12 00:22 UTC, jbis9051 commented on packages/rust/frontend/migrations/account/20230524013755_initial.up.sql
> +    location_date INTEGER NOT NULL,
TODO fix this

2023-07-12 00:24 UTC, jbis9051 commented on packages/rust/server/Cargo.toml
> +sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "sqlite", "postgres", "migrate", "uuid", "chrono"] }
@gannonsmith you can do

2023-07-12 00:24 UTC, jbis9051 commented on packages/rust/server/src/models/user.rs
> +    pub async fn client(&self, db: &DbPool) -> Result<Option<Client>, sqlx::Error> {
refactor this @gannonsmith

2023-07-12 12:16 UTC, merged